//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OtelKursach3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Классы.
    /// </summary>
    // *** Start programmer edit section *** (Классы CustomAttributes)

    // *** End programmer edit section *** (Классы CustomAttributes)
    public enum Классы
    {
        
        // *** Start programmer edit section *** (Классы.Элит CustomAttributes)

        // *** End programmer edit section *** (Классы.Элит CustomAttributes)
        [Caption("Элит")]
        Элит,
        
        // *** Start programmer edit section *** (Классы.Премиум CustomAttributes)

        // *** End programmer edit section *** (Классы.Премиум CustomAttributes)
        [Caption("Премиум")]
        Премиум,
        
        // *** Start programmer edit section *** (Классы.Бизнес CustomAttributes)

        // *** End programmer edit section *** (Классы.Бизнес CustomAttributes)
        [Caption("Бизнес")]
        Бизнес,
        
        // *** Start programmer edit section *** (Классы.Комфорт CustomAttributes)

        // *** End programmer edit section *** (Классы.Комфорт CustomAttributes)
        [Caption("Комфорт")]
        Комфорт,
        
        // *** Start programmer edit section *** (Классы.Эконом CustomAttributes)

        // *** End programmer edit section *** (Классы.Эконом CustomAttributes)
        [Caption("Эконом")]
        Эконом,
    }
}
