//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OtelKursach3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Комната.
    /// </summary>
    // *** Start programmer edit section *** (Комната CustomAttributes)

    // *** End programmer edit section *** (Комната CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КомнатаE", new string[] {
            "КодКомнаты as \'Код комнаты\'",
            "Стоимость as \'Стоимость\'",
            "Класс as \'Класс\'",
            "КолвоМест as \'Колво мест\'",
            "Отель as \'Отель\'",
            "Отель.Адрес as \'Адрес\'"}, Hidden=new string[] {
            "Отель.Адрес"})]
    [MasterViewDefineAttribute("КомнатаE", "Отель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [View("КомнатаL", new string[] {
            "КодКомнаты as \'Код комнаты\'",
            "Стоимость as \'Стоимость\'",
            "Класс as \'Класс\'",
            "КолвоМест as \'Колво мест\'",
            "Отель.Адрес as \'Адрес\'"})]
    public class Комната : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКомнаты;
        
        private int fСтоимость;
        
        private IIS.OtelKursach3.Классы fКласс;
        
        private IIS.OtelKursach3.Места fКолвоМест;
        
        private IIS.OtelKursach3.Отель fОтель;
        
        // *** Start programmer edit section *** (Комната CustomMembers)

        // *** End programmer edit section *** (Комната CustomMembers)

        
        /// <summary>
        /// Класс.
        /// </summary>
        // *** Start programmer edit section *** (Комната.Класс CustomAttributes)

        // *** End programmer edit section *** (Комната.Класс CustomAttributes)
        public virtual IIS.OtelKursach3.Классы Класс
        {
            get
            {
                // *** Start programmer edit section *** (Комната.Класс Get start)

                // *** End programmer edit section *** (Комната.Класс Get start)
                IIS.OtelKursach3.Классы result = this.fКласс;
                // *** Start programmer edit section *** (Комната.Класс Get end)

                // *** End programmer edit section *** (Комната.Класс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.Класс Set start)

                // *** End programmer edit section *** (Комната.Класс Set start)
                this.fКласс = value;
                // *** Start programmer edit section *** (Комната.Класс Set end)

                // *** End programmer edit section *** (Комната.Класс Set end)
            }
        }
        
        /// <summary>
        /// КодКомнаты.
        /// </summary>
        // *** Start programmer edit section *** (Комната.КодКомнаты CustomAttributes)

        // *** End programmer edit section *** (Комната.КодКомнаты CustomAttributes)
        public virtual int КодКомнаты
        {
            get
            {
                // *** Start programmer edit section *** (Комната.КодКомнаты Get start)

                // *** End programmer edit section *** (Комната.КодКомнаты Get start)
                int result = this.fКодКомнаты;
                // *** Start programmer edit section *** (Комната.КодКомнаты Get end)

                // *** End programmer edit section *** (Комната.КодКомнаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.КодКомнаты Set start)

                // *** End programmer edit section *** (Комната.КодКомнаты Set start)
                this.fКодКомнаты = value;
                // *** Start programmer edit section *** (Комната.КодКомнаты Set end)

                // *** End programmer edit section *** (Комната.КодКомнаты Set end)
            }
        }
        
        /// <summary>
        /// КолвоМест.
        /// </summary>
        // *** Start programmer edit section *** (Комната.КолвоМест CustomAttributes)

        // *** End programmer edit section *** (Комната.КолвоМест CustomAttributes)
        public virtual IIS.OtelKursach3.Места КолвоМест
        {
            get
            {
                // *** Start programmer edit section *** (Комната.КолвоМест Get start)

                // *** End programmer edit section *** (Комната.КолвоМест Get start)
                IIS.OtelKursach3.Места result = this.fКолвоМест;
                // *** Start programmer edit section *** (Комната.КолвоМест Get end)

                // *** End programmer edit section *** (Комната.КолвоМест Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.КолвоМест Set start)

                // *** End programmer edit section *** (Комната.КолвоМест Set start)
                this.fКолвоМест = value;
                // *** Start programmer edit section *** (Комната.КолвоМест Set end)

                // *** End programmer edit section *** (Комната.КолвоМест Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Комната.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Комната.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Комната.Стоимость Get start)

                // *** End programmer edit section *** (Комната.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (Комната.Стоимость Get end)

                // *** End programmer edit section *** (Комната.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.Стоимость Set start)

                // *** End programmer edit section *** (Комната.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Комната.Стоимость Set end)

                // *** End programmer edit section *** (Комната.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Комната.
        /// </summary>
        // *** Start programmer edit section *** (Комната.Отель CustomAttributes)

        // *** End programmer edit section *** (Комната.Отель CustomAttributes)
        [PropertyStorage(new string[] {
                "Отель"})]
        [NotNull()]
        public virtual IIS.OtelKursach3.Отель Отель
        {
            get
            {
                // *** Start programmer edit section *** (Комната.Отель Get start)

                // *** End programmer edit section *** (Комната.Отель Get start)
                IIS.OtelKursach3.Отель result = this.fОтель;
                // *** Start programmer edit section *** (Комната.Отель Get end)

                // *** End programmer edit section *** (Комната.Отель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.Отель Set start)

                // *** End programmer edit section *** (Комната.Отель Set start)
                this.fОтель = value;
                // *** Start programmer edit section *** (Комната.Отель Set end)

                // *** End programmer edit section *** (Комната.Отель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КомнатаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомнатаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомнатаE", typeof(IIS.OtelKursach3.Комната));
                }
            }
            
            /// <summary>
            /// "КомнатаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомнатаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомнатаL", typeof(IIS.OtelKursach3.Комната));
                }
            }
        }
    }
}
