//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OtelKursach3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр записи.
    /// </summary>
    // *** Start programmer edit section *** (РегистрЗаписи CustomAttributes)

    // *** End programmer edit section *** (РегистрЗаписи CustomAttributes)
    [AutoAltered()]
    [Caption("Регистр записи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрЗаписиE", new string[] {
            "КодРегитсра as \'Код регитсра\'",
            "ДатаЗаселения as \'Дата заселения\'",
            "ДатаВыезда as \'Дата выезда\'"})]
    public class РегистрЗаписи : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодРегитсра;
        
        private System.DateTime fДатаЗаселения;
        
        private System.DateTime fДатаВыезда;
        
        private IIS.OtelKursach3.Доступ fДоступ;
        
        // *** Start programmer edit section *** (РегистрЗаписи CustomMembers)

        // *** End programmer edit section *** (РегистрЗаписи CustomMembers)

        
        /// <summary>
        /// ДатаВыезда.
        /// </summary>
        // *** Start programmer edit section *** (РегистрЗаписи.ДатаВыезда CustomAttributes)

        // *** End programmer edit section *** (РегистрЗаписи.ДатаВыезда CustomAttributes)
        public virtual System.DateTime ДатаВыезда
        {
            get
            {
                // *** Start programmer edit section *** (РегистрЗаписи.ДатаВыезда Get start)

                // *** End programmer edit section *** (РегистрЗаписи.ДатаВыезда Get start)
                System.DateTime result = this.fДатаВыезда;
                // *** Start programmer edit section *** (РегистрЗаписи.ДатаВыезда Get end)

                // *** End programmer edit section *** (РегистрЗаписи.ДатаВыезда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрЗаписи.ДатаВыезда Set start)

                // *** End programmer edit section *** (РегистрЗаписи.ДатаВыезда Set start)
                this.fДатаВыезда = value;
                // *** Start programmer edit section *** (РегистрЗаписи.ДатаВыезда Set end)

                // *** End programmer edit section *** (РегистрЗаписи.ДатаВыезда Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗаселения.
        /// </summary>
        // *** Start programmer edit section *** (РегистрЗаписи.ДатаЗаселения CustomAttributes)

        // *** End programmer edit section *** (РегистрЗаписи.ДатаЗаселения CustomAttributes)
        public virtual System.DateTime ДатаЗаселения
        {
            get
            {
                // *** Start programmer edit section *** (РегистрЗаписи.ДатаЗаселения Get start)

                // *** End programmer edit section *** (РегистрЗаписи.ДатаЗаселения Get start)
                System.DateTime result = this.fДатаЗаселения;
                // *** Start programmer edit section *** (РегистрЗаписи.ДатаЗаселения Get end)

                // *** End programmer edit section *** (РегистрЗаписи.ДатаЗаселения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрЗаписи.ДатаЗаселения Set start)

                // *** End programmer edit section *** (РегистрЗаписи.ДатаЗаселения Set start)
                this.fДатаЗаселения = value;
                // *** Start programmer edit section *** (РегистрЗаписи.ДатаЗаселения Set end)

                // *** End programmer edit section *** (РегистрЗаписи.ДатаЗаселения Set end)
            }
        }
        
        /// <summary>
        /// КодРегитсра.
        /// </summary>
        // *** Start programmer edit section *** (РегистрЗаписи.КодРегитсра CustomAttributes)

        // *** End programmer edit section *** (РегистрЗаписи.КодРегитсра CustomAttributes)
        public virtual int КодРегитсра
        {
            get
            {
                // *** Start programmer edit section *** (РегистрЗаписи.КодРегитсра Get start)

                // *** End programmer edit section *** (РегистрЗаписи.КодРегитсра Get start)
                int result = this.fКодРегитсра;
                // *** Start programmer edit section *** (РегистрЗаписи.КодРегитсра Get end)

                // *** End programmer edit section *** (РегистрЗаписи.КодРегитсра Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрЗаписи.КодРегитсра Set start)

                // *** End programmer edit section *** (РегистрЗаписи.КодРегитсра Set start)
                this.fКодРегитсра = value;
                // *** Start programmer edit section *** (РегистрЗаписи.КодРегитсра Set end)

                // *** End programmer edit section *** (РегистрЗаписи.КодРегитсра Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.OtelKursach3.Доступ.
        /// </summary>
        // *** Start programmer edit section *** (РегистрЗаписи.Доступ CustomAttributes)

        // *** End programmer edit section *** (РегистрЗаписи.Доступ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Доступ"})]
        public virtual IIS.OtelKursach3.Доступ Доступ
        {
            get
            {
                // *** Start programmer edit section *** (РегистрЗаписи.Доступ Get start)

                // *** End programmer edit section *** (РегистрЗаписи.Доступ Get start)
                IIS.OtelKursach3.Доступ result = this.fДоступ;
                // *** Start programmer edit section *** (РегистрЗаписи.Доступ Get end)

                // *** End programmer edit section *** (РегистрЗаписи.Доступ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрЗаписи.Доступ Set start)

                // *** End programmer edit section *** (РегистрЗаписи.Доступ Set start)
                this.fДоступ = value;
                // *** Start programmer edit section *** (РегистрЗаписи.Доступ Set end)

                // *** End programmer edit section *** (РегистрЗаписи.Доступ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрЗаписиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрЗаписиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрЗаписиE", typeof(IIS.OtelKursach3.РегистрЗаписи));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of РегистрЗаписи.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfРегистрЗаписи CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfРегистрЗаписи CustomAttributes)
    public class DetailArrayOfРегистрЗаписи : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.OtelKursach3.DetailArrayOfРегистрЗаписи members)

        // *** End programmer edit section *** (IIS.OtelKursach3.DetailArrayOfРегистрЗаписи members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type РегистрЗаписи by index.
        /// </summary>
        /// <summary>
        /// Adds object with type РегистрЗаписи.
        /// </summary>
        public DetailArrayOfРегистрЗаписи(IIS.OtelKursach3.Доступ fДоступ) : 
                base(typeof(РегистрЗаписи), ((ICSSoft.STORMNET.DataObject)(fДоступ)))
        {
        }
        
        public IIS.OtelKursach3.РегистрЗаписи this[int index]
        {
            get
            {
                return ((IIS.OtelKursach3.РегистрЗаписи)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.OtelKursach3.РегистрЗаписи dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
